package lnq.com.lnq.endpoints;

public interface EndpointKeys {

    String X_API_KEY = "1DE4D54049DBAB7A43BCAE5860C6A2F5A03413D39691C46B23B08F0B861F2B57";

    //    Bundle keys....
    String OPEN_LOGIN = "open_login";
    String ON_BOARD_TUTORIAL_TYPE = "on_board_tutorial_type";
    String INTRODUCTION = "introduction";
    String GUID_LINE = "guid_line";
    String EMAIL = "email";
    String EMAIL_SENT_TYPE = "email_sent_type";
    String FIRST_NAME = "first_name";
    String LAST_NAME = "last_name";
    String IMAGE_PATH = "image_path";
    String TYPE = "type";
    String USER_ID = "user_id";
    String USER_NAME = "user_name";
    String USER_CONNECTION_STATUS = "user_connection_status";
    String IS_USER_FAVORITE = "is_user_favorite";
    String IS_LOCATION_HIDDEN = "is_location_hidden";
    String IS_FAVORITE = "is_favorite";
    String ACTIVITY_TYPE = "activity_type";
    String IS_BLOCK = "is_block";
    String THREAD_ID = "thread_id";
    String CHAT_UNREAD_COUNT = "chat_unread_count";
    String RECEIVER_ID = "receiver_id";
    String SENDER_ID = "sender_id";
    String CURRENT_FRAGMENT = "chat";
    String NOTIFICATION_STATUS = "notification_status";
    //    Retrofit serialize keys....
    String ID = "id";
    String ID_PROFILE = "id_profile";
    String SUBJECT = "SUBJECT";
    String MESSAGE = "MESSAGE";
    String USER_EMAIL = "user_email";
    String USER_PASS = "user_pass";
    String USER_TYPE = "user_type";
    String USER_STATUS = "user_status";
    String DEVICE_TYPE = "device_type";
    String DEVICE_TOCKEN = "device_tocken";
    String USER_LOCATION = "user_location";
    String UPDATED_AT = "updated_at";
    String CREATED_AT = "created_at";
    String USER_CNIC = "user_cnic";
    String USER_Gender = "user_gender";
    String USER_SECONDARY_Gender = "user_secondary_gender";

    //    Shared preference keys....
    String VERIFICATION_STATUS = "verification_status";
    String IS_USER_LOGGED_IN = "is_user_logged_in";
    String SIGN_UP = "signup";
    String FIRSTNAME_LASTNAME = "firstname_lastname";
    String PHONE = "phone";
    String PROFILE = "profile";
    String PROFILE_IMAGE = "profile_image";
    String VISIBLE_TO = "visible_to";
    String VISIBLE_AT = "visible_at";
    String IS_LOGGEN_IN = "is_logged_in";
    String FCM_TOKEN = "fcm_token";
    String USER_FNAME = "user_fname";
    String USER_SECONDARY_FNAME = "user_secondary_fname";
    String USER_LNAME = "user_lname";
    String USER_SECONDARY_LNAME = "user_secondary_lname";
    String USER_AVATAR = "user_avatar";
    String USER_SECONDARY_AVATAR = "user_secondary_avatar";
    String GROUP_NAME = "group_name";
    String GROUP_USERNAMES = "group_usernames";
    String GROUP_CHAT_THREAD_ID = "group_chat_thread_id";
    String GROUP_USER_NAMES = "group_user_names";
    String GROUP_USERS_IDS = "group_users_ids";
    String GROUP_USERS_PROFILE_IDS = "group_users_profile_ids";
    String USER_PHONE = "user_phone";
    String USER_SECONDARY_EMAILS = "secondary_emails";
    String USER_SECONDARY_PHONES = "secondary_phones";
    String USER_SOCIAL_LINK = "social_link";
    String USER_SECONDARY_SOCIAL_LINK = "secondary_social_link";
    String USER_BIRTHDAY = "user_birthday";
    String USER_SECONDARY_BIRTHDAY = "user_secondary_birthday";
    String USER_BIO = "user_bio";
    String USER_SECONDARY_BIO = "user_secondary_bio";
    String USER_ADDRESS = "user_address";
    String USER_SECONDARY_ADDRESS = "user_secondary_address";
    String USER_CURRENT_POSITION = "user_current_position";
    String USER_SECONDARY_CURRENT_POSITION = "user_secondary_current_position";
    String USER_COMPANY = "user_company";
    String USER_SECONDARY_COMPANY = "user_secondary_company";
    String USER_STATUS_MESSAGE = "user_status_msg";
    String USER_SECONDARY_STATUS_MESSAGE = "user_secondary_status_msg";
    String USER_INTRESTS = "user_interests";
    String USER_SECONDARY_INTRESTS = "user_secondary_interests";
    String SHOW_NOTIFICATION_DIALOG = "show_notification_dialog";
    String CONNECTION_COUNT = "connection_count";
    String PROFILE_CREATED_DATE = "profile_created_date";
    String USER_PASSWORD = "user_password";
    String AVATAR_FROM = "avatar_from";
    String SEARCH_TEXT = "search_text";
    String USER_FILTERS = "user_filters";
    String USER_SORTING = "user_sorting";
    String SORT_ALPHABETICAL = "alphabet";
    String SORT_DISTANC = "distance";
    String SORT_RECENTLNQ = "recentlnq";
    String SORT_RECENTVIEWED = "recentviewed";
    String FREEZE_USER = "freeze";
    String UN_FREEZE_USER = "unfreeze";
    String IS_FROZEN = "is_frozen";
    String STATUS_DATE = "status_date";
    String LAST_LOGIN = "last_login";
    String MAPVIEW = "mapView";
    String CONNECTIONVIEW = "connectionView";

    //     Geo code keys....
    String LATLNG = "latlng";
    String SENSOR = "sensor";
    String LANGUAGE = "language";
    String RESULTS = "results";
    String ADDRESS_COMPONENTS = "address_components";
    String SHORT_NAME = "short_name";
    String LONG_NAME = "long_name";
    String TYPES = "types";
    String ADMINISTRATIVE_AREA_LEVEL_2 = "administrative_area_level_2";
    String ADMINISTRATIVE_AREA_LEVEL_1 = "administrative_area_level_1";
    String COUNTRY = "country";
    String POSTAL_CODE = "postal_code";
    String KEY = "key";
    String PREMISE = "premise";
    String STREET_NO = "street_number";
    String ROUTE = "route";
    String NEIGHBORHOOD = "neighborhood";
    String SUB_LOCALITY_2 = "sublocality_level_2";
    String SUB_LOCALITY_1 = "sublocality_level_1";
    String VERIFICATION_TYPE = "verification_type";

    //    Event bus keys....
    String IMPORT = "import";
    String EXPORT = "export";

    String PROFILE_ID = "profile_id";
    String PROFILE_ID_CHAT = "CHAT_profileId";
}
